In [1]:
import pandas as pd

In [2]:
path = "/home/aszummer/Documents/MCV/M6/mcvm6team3/experiments/det_S01_c002/dets.txt"

In [3]:
COL_NAMES = ['frame','wtf', 'bb_left', 'bb_top', 'bb_width', 'bb_height', 'conf','del','del1', 'del2']

predictions_dict = {}
df = pd.read_csv(path, delimiter=',', names=COL_NAMES)

In [5]:
df.head()

frame  wtf      bb_left      bb_top    bb_width   bb_height      conf  del  \
0      1   -1   125.547150  457.378235  497.644684  192.784485  0.995978   -1   
1      1   -1   908.480835  215.337616   93.613708   93.334076  0.977238   -1   
2      1   -1   867.040527  165.821320   71.281250   49.733170  0.976740   -1   
3      1   -1  1265.807617  277.298828   95.997681   82.097351  0.943682   -1   
4      1   -1  1312.205444  108.778412   60.943726   21.335312  0.908940   -1   

   del1  del2  
0    -1    -1  
1    -1    -1  
2    -1    -1  
3    -1    -1  
4    -1    -1

In [9]:
df.shape

(69133, 10)

In [39]:
df_test = df
df_bigger_then_1000 = df_test[(df_test['bb_width'] * df_test['bb_height']) > 3000]
df_without_top_10 = df_bigger_then_1000[df_bigger_then_1000['bb_top']>100]

In [40]:
df_bigger_then_1000.shape

(17545, 10)

In [41]:
df_without_top_10.shape

(13807, 10)

In [42]:
df_without_top_10.to_csv('dets_small.txt', index=False, header=False)

In [38]:
df_smaller_then_1000

frame  wtf     bb_left     bb_top   bb_width  bb_height      conf  del  \
5          1   -1  722.762756  77.787109  29.893250  20.512169  0.780833   -1   
8          1   -1  230.793289  41.624142  21.263458  20.091164  0.320179   -1   
9          1   -1  408.770050  51.349976  21.667969  17.348450  0.315587   -1   
10         1   -1  767.977417  59.644451  20.173096  14.311771  0.303920   -1   
11         1   -1  385.498657  69.868347  28.111816  17.983971  0.291241   -1   
...      ...  ...         ...        ...        ...        ...       ...  ...   
69126   2110   -1  677.853638  68.620316  47.970886  20.835640  0.088422   -1   
69127   2110   -1  304.598511  46.034626  34.343506  17.424938  0.083232   -1   
69130   2110   -1  729.489075  69.916748  30.737549  24.011948  0.059890   -1   
69131   2110   -1  313.558990  50.790253  33.528168  14.834183  0.059227   -1   
69132   2110   -1  734.423035  79.524025  20.255737  19.135857  0.054960   -1   

       del1  del2  
5        -1    -1  
8        -1    -1  
9        -1    -1  
10       -1    -1  
11       -1    -1  
...     ...   ...  
69126    -1    -1  
69127    -1    -1  
69130    -1    -1  
69131    -1    -1  
69132    -1    -1  

[39357 rows x 10 columns]

In [17]:
path  = '/home/aszummer/Documents/MCV/M6/mcvm6team3/experiments/FasterRCNN_finetune_S01_S04_e2/S03/c010/features.txt'

'0'

In [19]:
COL_NAMES = [str(x) for x in range(0,512)]
COL_NAMES[0]
df = pd.read_csv(path, delimiter=',', names=COL_NAMES)

In [25]:
df

0       1       2       3       4       5       6       7       8  \
0  0.0462 -0.1063 -0.0272 -0.0048  0.0343  0.1125  0.0525 -0.0468  0.0044   
1  0.1038 -0.0744  0.0269 -0.0028  0.0838  0.0215  0.0288  0.0136 -0.0070   

        9  ...     502     503     504     505     506     507     508  \
0  0.0152  ...  0.0042  0.0066  0.0747 -0.0256 -0.0021 -0.0465 -0.0116   
1 -0.0160  ... -0.0060  0.0101  0.0295 -0.0448 -0.0057  0.0184  0.0780   

      509     510     511  
0 -0.0554 -0.0288  0.0117  
1  0.0015 -0.0986  0.0743  

[2 rows x 512 columns]

In [56]:
df.shape

(2, 512)

In [57]:
list_of_feature_vectors = []
for row in range(df.shape[0]):
    tab = np.array(df.iloc[row])
    tab = tab.reshape((1,512))
    tab_torch = torch.from_numpy(tab).type(torch.float32)
    list_of_feature_vectors.append(tab_torch)

In [61]:
list_of_feature_vectors[0][0][0]

tensor(0.0462)

In [21]:
import numpy as np
import torch

In [36]:
tab = np.array(df.iloc[0])


In [37]:
tab = tab.reshape((1,512))

In [38]:
tab.shape

(1, 512)

In [40]:
tab_torch = torch.from_numpy(tab).type(torch.float32)

0.0462

In [53]:
tab_torch[0][0]

tensor(0.0462)

In [49]:
tab_torch = torch.from_numpy(tab).type(torch.float32)

In [51]:
tab_torch[0][0].dtype

torch.float32

In [63]:
col = [1,2,3]
col.insert(0,'frame')
col

['frame', 1, 2, 3]

In [67]:
df.iloc[0,0:]

0      0.0462
1     -0.1063
2     -0.0272
3     -0.0048
4      0.0343
        ...  
507   -0.0465
508   -0.0116
509   -0.0554
510   -0.0288
511    0.0117
Name: 0, Length: 512, dtype: float64

In [68]:
path  = '/home/aszummer/Documents/MCV/M6/mcvm6team3/experiments/FasterRCNN_finetune_S01_S04_e2/S03/c010/features.txt'

In [69]:
COL_NAMES = [str(x) for x in range(0,512)]
COL_NAMES[0]
df = pd.read_csv(path, delimiter=',', names=COL_NAMES)

In [70]:
df.shape

(9432, 512)

In [71]:
path  = '/home/aszummer/Documents/MCV/M6/mcvm6team3/experiments/FasterRCNN_finetune_S01_S04_e2/S03/c010/features0.5.txt'
COL_NAMES = [str(x) for x in range(0,512)]
COL_NAMES[0]
df = pd.read_csv(path, delimiter=',', names=COL_NAMES)
df.shape


(5664, 512)

In [72]:
from pathlib import Path

In [84]:
path_to_seqs = Path("/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train")
paths_to_seqs = list(path_to_seqs.iterdir())
for sequences in paths_to_seqs:
    paths_to_cams = list(sequences.iterdir())
    print(sequences)
    for cams in paths_to_cams:
        path_input = str(cams/'vdo.avi')
        print(path_input)
        break



/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S01
/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S01/c002/vdo.avi
/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S03
/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S03/c011/vdo.avi
/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04
/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c027/vdo.avi


In [82]:
paths_to_cams

[PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c027'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c023'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c026'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c028'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c030'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c025'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c038'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c019'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-train/train/S04/c020'),
 PosixPath('/home/aszummer/Documents/MCV/M6/mcvm6team3/data/aic19-track1-mtmc-trai

In [97]:
    path = '/home/aszummer/Documents/MCV/M6/mcvm6team3/experiments/FasterRCNN_finetune_S01_S03_e2/S04/c016/features_all.txt'
    
    COL_NAMES = [str(x) for x in range(0,512)]
    COL_NAMES.insert(0,'frame')
    df = pd.read_csv(path, delimiter=',', names=COL_NAMES)

    list_of_feature_vectors = []
    for row in range(df.shape[0]):
        tab = np.array(df.iloc[row,1:])
        tab = tab.reshape((1,512))
        tab_torch = torch.from_numpy(tab).type(torch.float32)
        list_of_feature_vectors.append(tab_torch)
    
    result = [df['frame'].values, np.array(list_of_feature_vectors)]

<ipython-input-97-04d9f57f43b6>:14: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  result = [df['frame'].values, np.array(list_of_feature_vectors)]
<ipython-input-97-04d9f57f43b6>:14: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = [df['frame'].values, np.array(list_of_feature_vectors)]


In [92]:
result[0][result[0]==309]

array([309, 309, 309, 309, 309, 309, 309, 309, 309, 309, 309])

In [98]:
    path = '/home/aszummer/Documents/MCV/M6/mcvm6team3/experiments/FasterRCNN_finetune_S01_S03_e2/S04/c016/dets_all.txt'
    COL_NAMES = ['frame', 'bb_left', 'bb_top', 'bb_width', 'bb_height', 'conf']

    predictions_dict = {}
    df_det = pd.read_csv(path, delimiter=',', usecols=[0, 2, 3, 4, 5, 6], names=COL_NAMES)

In [99]:
df.head()

frame       0       1       2       3       4       5       6       7  \
0      1  0.0061 -0.0696  0.0018  0.0354  0.0757  0.0263 -0.0288 -0.0413   
1      1 -0.0641 -0.1053  0.0365  0.0032  0.0710  0.0356 -0.0260 -0.0189   
2      1  0.0408 -0.0635  0.0014  0.0403  0.0773 -0.0012 -0.0162 -0.0112   
3      1  0.0338 -0.0739  0.0118 -0.0036  0.0940  0.0213  0.0139 -0.0108   
4      2  0.0184 -0.0804  0.0019  0.0571  0.0915  0.0087 -0.0269 -0.0446   

        8  ...     502     503     504     505     506     507     508  \
0  0.0502  ... -0.0745  0.0215  0.0926 -0.0484 -0.0026  0.0166 -0.0003   
1  0.0146  ...  0.0059 -0.0203  0.1254  0.0325  0.0278 -0.0297  0.0393   
2  0.0291  ... -0.0634  0.0674  0.0378 -0.0326  0.0007 -0.0230 -0.0184   
3  0.0113  ... -0.0442  0.0201  0.0556  0.0002 -0.0756 -0.0360 -0.0293   
4  0.0537  ... -0.0736  0.0234  0.0793 -0.0278 -0.0035  0.0330  0.0248   

      509     510     511  
0  0.0623 -0.0340  0.0427  
1 -0.0606 -0.0739  0.0145  
2  0.0674  0.0077  0.0348  
3  0.0566  0.0161  0.0064  
4  0.0524 -0.0427  0.0500  

[5 rows x 513 columns]

In [101]:
df_det.head()

frame     bb_left      bb_top    bb_width   bb_height      conf
0      1  316.709045  537.927734  247.655273  209.197083  0.984004
1      1  931.526917  205.843292  150.732727  138.890839  0.981314
2      1  367.508270  521.147339  306.098114  251.334656  0.171370
3      1  359.552795  565.025757  385.375000  331.139648  0.083068
4      2  311.824799  544.120544  251.915924  205.270142  0.984537

In [117]:
df_det.groupby('frame')['bb_left'].unique()

frame
1      [316.70904541015625, 931.5269165039062, 367.50...
2      [311.8247985839844, 934.9119262695312, 365.831...
3      [301.69244384765625, 940.2626342773438, 376.74...
4      [294.7429504394531, 941.4710693359376, 458.783...
5      [287.42303466796875, 942.1107177734376, 378.75...
                             ...                        
306    [1075.0899658203125, 888.6000366210938, 240.13...
307    [1082.55615234375, 865.6908569335938, 1045.269...
308    [1090.7509765625, 855.5480346679688, 1039.7692...
309    [1096.671875, 1037.142578125, 845.057434082031...
310    [1106.5040283203125, 1036.482177734375, 382.65...
Name: bb_left, Length: 310, dtype: object

In [121]:
df['frame'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  51,  52,  53,  55,
        56,  57,  58,  59,  60,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
       123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
       136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
       149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
       175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 18

In [119]:
df_det['frame'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [123]:
df_det[df_det['frame']==49]

frame      bb_left      bb_top    bb_width   bb_height      conf
217     49  1180.330078  115.781372  133.687744  111.086182  0.134692
218     49   402.789337  289.551483  385.764923  264.607941  0.054353